/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.devopsds8;

import java.util.Date;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static long getJvmTime() {
        return System.currentTimeMillis();
    }

    public  static Date getJvmDate() {
        return new Date();
    }

    public static String getJvmUtcDateOnly() {
        ZonedDateTime now = ZonedDateTime.now(ZoneOffset.UTC);
        String utcDate = formatDateToUTC(now);
        return utcDate;
    }

    public static String formatDateToUTC(ZonedDateTime date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z").withZone(ZoneOffset.UTC);
        return date.format(formatter);
    }
}

